<a href="https://colab.research.google.com/github/auroravicks/ML_Projects/blob/main/ML_Practical_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

df=pd.read_csv('iris.csv')

In [ ]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
X=df.drop('class',axis=1)
y=df['class']
print(X.shape,y.shape)
#preprocessing

(150, 4) (150,)


In [ ]:
#svm linear

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

from sklearn.svm import SVC
clf = SVC(kernel='linear')

clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
#print ("Confusion Matrix : \n", cm)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Confusion Matrix : 
 [[15  0  0]
 [ 0 14  2]
 [ 0  0 14]]
Accuracy :  0.9555555555555556


In [ ]:
#svm non linear (polynomial)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

from sklearn.svm import SVC
clf = SVC(kernel='poly')

clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Confusion Matrix : 
 [[15  0  0]
 [ 0 15  1]
 [ 0  0 14]]
Accuracy :  0.9777777777777777


In [ ]:
#svm non linear (radial basis function)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

from sklearn.svm import SVC
clf = SVC(kernel='rbf')

clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Confusion Matrix : 
 [[15  0  0]
 [ 0 15  1]
 [ 0  0 14]]
Accuracy :  0.9777777777777777
